# -*- coding: utf-8 -*-
"""ViT-GPT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sqj2eBbxM1_8GRRoCJpYeDGcazWauMye

# **Setup the environment**
"""

!pip install -q transformers datasets evaluate rouge-score gradio

"""# **Space Image Captioning with ViT-GPT2**

## Problem Statement
Given an image of a space object (galaxy, nebula, planet, star cluster),
automatically generate a short descriptive caption.

## Model Choice: ViT-GPT2
We use `nlpconnect/vit-gpt2-image-captioning`, a Vision Encoder-Decoder model:
- **ViT (encoder)**: splits the image into 16×16 patches, processes them
  as a sequence using self-attention across 12 transformer layers
- **GPT-2 (decoder)**: generates captions word-by-word using cross-attention
  to "look at" the image while writing

## Why this model?
- Directly covers Transformers, ViTs, and pretrained models (rubric focus)
- End-to-end: takes image → outputs text with no intermediate steps
- Strong pretrained base (COCO dataset, 330k images) to fine-tune from

# **Dataset Loading & Exploration**

We use our own NASA space image dataset stored locally.
"""

from google.colab import files
import zipfile
import os

# Step 1: upload CSV
print("Upload vlm_captions_dataset.csv")
uploaded = files.upload()

# Step 2: upload images zip
print("\nUpload vlm_images.zip")
uploaded = files.upload()
zip_name = list(uploaded.keys())[0]
print(f"Extracting {zip_name}...")
with zipfile.ZipFile(zip_name, 'r') as z:
    z.extractall(".")

print(f"\nCSV exists: {os.path.exists('vlm_captions_dataset.csv')}")
print(f"Images exist: {os.path.exists('vlm_images')}")

import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import os

CSV_PATH   = "vlm_captions_dataset.csv"
IMAGES_DIR = "vlm_images"

df = pd.read_csv(CSV_PATH)
print(f"Total rows: {len(df)}")
print(df.head())
print(f"\nCategories:\n{df['category'].value_counts()}")

"""**Clean captions:**
 * Some rows have caption = title (short, useless for training).
*  We use the caption only if it's meaningfully longer than the title,
 otherwise we fall back to the title itself.

**Drop rows where the image file doesn't exist on disk**
"""

df = pd.read_csv(CSV_PATH)

df['text'] = df.apply(
    lambda row: row['caption']
    if isinstance(row['caption'], str)
    and len(row['caption']) > len(str(row['title'])) + 20
    else row['title'],
    axis=1
)

# Drop rows where image doesn't exist on disk

df = df[df['image_file_path'].apply(
    lambda p: os.path.exists(os.path.join(IMAGES_DIR, os.path.basename(p)))
)].reset_index(drop=True)

print(f"Rows after cleaning: {len(df)}")
print(f"Sample path check: {df['image_file_path'].iloc[0]}")

"""**Visualize 8 sample images with their captions**"""

fig, axes = plt.subplots(2, 4, figsize=(16, 8))
for i, ax in enumerate(axes.flat):
    row = df.iloc[i]
    img_path = os.path.join(IMAGES_DIR, os.path.basename(row['image_file_path']))
    img = Image.open(img_path).convert("RGB")
    ax.imshow(img)
    ax.set_title(f"[{row['category']}]\n{row['text'][:50]}...", fontsize=7)
    ax.axis('off')
plt.suptitle("Sample space images with captions", fontsize=13)
plt.tight_layout()
plt.savefig("dataset_samples.png")
plt.show()

"""# **Load Pretrained Model**

* We load **ViT-GPT2** from HuggingFace.
At this stage the model has no knowledge
of space images — it was trained on COCO (everyday objects like dogs, cars, people).
We will test it as-is first to establish a baseline, then fine-tune it.
"""

import torch
from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

MODEL_NAME = "nlpconnect/vit-gpt2-image-captioning"

model             = VisionEncoderDecoderModel.from_pretrained(MODEL_NAME)
feature_extractor = ViTImageProcessor.from_pretrained(MODEL_NAME)
tokenizer         = AutoTokenizer.from_pretrained(MODEL_NAME)

# Required: set special tokens for the decoder
tokenizer.pad_token                          = tokenizer.eos_token
model.config.pad_token_id                    = tokenizer.pad_token_id
model.config.decoder_start_token_id          = tokenizer.bos_token_id

model.to(device)
print("Model loaded ✓")

# Generation parameters
gen_kwargs = {
    "max_length": 50,           # max caption length
    "num_beams": 4,             # beam search: explore 4 paths, pick best
    "no_repeat_ngram_size": 2,  # prevent repeated phrases
    "early_stopping": True,
    "length_penalty": 1.0,
}

def generate_caption(image: Image.Image) -> str:
    if image.mode != "RGB":
        image = image.convert("RGB")
    pixel_values = feature_extractor(
        images=image, return_tensors="pt"
    ).pixel_values.to(device)
    with torch.no_grad():
        output_ids = model.generate(pixel_values, **gen_kwargs)
    return tokenizer.decode(output_ids[0], skip_special_tokens=True).strip()

""" **Baseline Evaluation — Zero-shot**
* We run the model AS-IS on 5 space images before any fine-tuning.
 * Expected result: poor captions describing everyday objects, not space.
* **This is our baseline — we compare against this after fine-tuning.**


"""

print("=== BASELINE (no fine-tuning) ===\n")
baseline_results = []

for i in range(5):
    row = df.iloc[i]
    img_path = os.path.join(IMAGES_DIR, os.path.basename(row['image_file_path']))
    img = Image.open(img_path).convert("RGB")
    pred = generate_caption(img)
    true = row['text']
    baseline_results.append({"true": true, "predicted": pred})
    print(f"[{row['category']}]")
    print(f"  True:      {true[:80]}")
    print(f"  Predicted: {pred}")
    print()

"""## **Fine-tuning on Space Images**
The pretrained model describes space images as everyday objects because
it has never seen space data.**We fine-tune it on our NASA dataset so it**
learns domain-specific vocabulary: "nebula", "galaxy", "planetary surface", etc.

Why fine-tune instead of train from scratch?
*- ViT already knows how to see (edges, shapes, textures)
- GPT-2 already knows how to write (grammar, sentence structure)
- Fine-tuning teaches space vocabulary on top of that existing knowledge
"""

from torch.utils.data import Dataset
from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments, default_data_collator
from sklearn.model_selection import train_test_split

class SpaceCaptionDataset(Dataset):
    def __init__(self, dataframe, images_dir, feature_extractor, tokenizer, max_length=50):
        self.df                = dataframe.reset_index(drop=True)
        self.images_dir        = images_dir
        self.feature_extractor = feature_extractor
        self.tokenizer         = tokenizer
        self.max_length        = max_length

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = os.path.join(self.images_dir, os.path.basename(row['image_file_path']))
        image = Image.open(img_path).convert("RGB")
        pixel_values = self.feature_extractor(
            images=image, return_tensors="pt"
        ).pixel_values.squeeze(0)

        labels = self.tokenizer(
            row['text'],
            max_length=self.max_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt"
        ).input_ids.squeeze(0)

        # -100 = ignore padding in loss calculation
        labels[labels == self.tokenizer.pad_token_id] = -100

        return {"pixel_values": pixel_values, "labels": labels}

# 80/20 split
train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)
print(f"Train: {len(train_df)} | Val: {len(val_df)}")

train_dataset = SpaceCaptionDataset(train_df, IMAGES_DIR, feature_extractor, tokenizer)
val_dataset   = SpaceCaptionDataset(val_df,   IMAGES_DIR, feature_extractor, tokenizer)

OUTPUT_DIR = "./space-captioning-finetuned"

training_args = Seq2SeqTrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=10,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    learning_rate=5e-5,
    warmup_steps=50,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    predict_with_generate=True,
    logging_steps=10,
    fp16=torch.cuda.is_available(),
    report_to="none",
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=default_data_collator,
)

print("Starting fine-tuning...")
trainer.train()

trainer.save_model(OUTPUT_DIR)

# Save tokenizer and processor
tokenizer.save_pretrained(OUTPUT_DIR)
feature_extractor.save_pretrained(OUTPUT_DIR)

print(f"Model saved to {OUTPUT_DIR} ✓")

FINAL_DIR = "./final_model"

trainer.save_model(FINAL_DIR)
tokenizer.save_pretrained(FINAL_DIR)
feature_extractor.save_pretrained(FINAL_DIR)

print(f"Final model saved to {FINAL_DIR} ✓")

!zip -r final_model.zip final_model

from google.colab import drive
drive.mount('/content/drive')

!cp final_model.zip /content/drive/MyDrive/

# Unzip the saved model from Drive
!unzip -q /content/drive/MyDrive/final_model.zip -d /content/
OUTPUT_DIR = "/content/final_model"
print(f"Model exists: {os.path.exists(OUTPUT_DIR)}")

"""## **Evaluation — Baseline vs Fine-tuned**
 **We compare captions before and after fine-tuning using BLEU score**.
* BLEU measures n-gram overlap between predicted and reference captions.
* Range: 0 (no match) → 1 (perfect match).
"""

from transformers import VisionEncoderDecoderModel
import evaluate
import nltk
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

bleu_metric = evaluate.load("bleu")

def evaluate_model_bleu(mdl, dataframe):
    mdl.eval()
    predictions, references = [], []
    for i in range(len(dataframe)):
        row = dataframe.iloc[i]
        img = Image.open(
            os.path.join(IMAGES_DIR, os.path.basename(row['image_file_path']))
        ).convert("RGB")
        pixel_values = feature_extractor(
            images=img, return_tensors="pt"
        ).pixel_values.to(device)
        with torch.no_grad():
            output_ids = mdl.generate(pixel_values, **gen_kwargs)
        pred = tokenizer.decode(output_ids[0], skip_special_tokens=True).strip()
        predictions.append(pred)
        references.append([row['text']])
    score = bleu_metric.compute(predictions=predictions, references=references)
    return score['bleu'], predictions, references

# Load both models
model_baseline  = VisionEncoderDecoderModel.from_pretrained(MODEL_NAME).to(device)
model_finetuned = VisionEncoderDecoderModel.from_pretrained(OUTPUT_DIR).to(device)

print("Evaluating baseline...")
bleu_base, preds_base, refs = evaluate_model_bleu(model_baseline, val_df)

print("Evaluating fine-tuned...")
bleu_ft, preds_ft, _ = evaluate_model_bleu(model_finetuned, val_df)

print(f"\n{'='*45}")
print(f"Baseline   BLEU: {bleu_base:.4f}")
print(f"Fine-tuned BLEU: {bleu_ft:.4f}")
print(f"Improvement:    +{(bleu_ft - bleu_base):.4f}")
print(f"{'='*45}")

# Side-by-side comparison
print("\n=== Caption Comparison ===\n")
for i in range(5):
    row = val_df.iloc[i]
    print(f"[{row['category']}]")
    print(f"  Reference:  {refs[i][0][:80]}")
    print(f"  Baseline:   {preds_base[i]}")
    print(f"  Fine-tuned: {preds_ft[i]}")
    print()

"""## **Error Analysis & Reflection**
* We find the 4 worst predictions from the fine-tuned model **(lowest BLEU)**
and analyze why the model failed on those specific images.
* Understanding failures shows deeper model knowledge
"""

from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

per_sample_bleu = [
    sentence_bleu(
        [refs[i][0].split()],
        preds_ft[i].split(),
        smoothing_function=SmoothingFunction().method1
    )
    for i in range(len(preds_ft))
]

worst_indices = sorted(range(len(per_sample_bleu)), key=lambda i: per_sample_bleu[i])[:4]

print("=== 4 Worst Predictions ===\n")
fig, axes = plt.subplots(1, 4, figsize=(16, 5))
for ax, idx in zip(axes, worst_indices):
    row = val_df.iloc[idx]
    img = Image.open(
        os.path.join(IMAGES_DIR, os.path.basename(row['image_file_path']))
    ).convert("RGB")
    ax.imshow(img)
    ax.set_title(
        f"BLEU={per_sample_bleu[idx]:.2f}\n"
        f"Ref: {refs[idx][0][:40]}...\n"
        f"Pred: {preds_ft[idx][:40]}...",
        fontsize=6
    )
    ax.axis('off')
plt.tight_layout()
plt.savefig("error_analysis.png")
plt.show()

"""###**Reflection**
**Error Analysis**

### Error Analysis

**All 4 worst predictions score BLEU=0.00**not because they are completely
wrong,
* but because BLEU requires exact n-gram matches and our reference
captions contain highly specific catalog numbers, dates, and object names
(e.g. "NGC 362", "01 January 2000") that the model cannot reproduce exactly
from visual input alone.

* Qualitatively the predictions show clear improvement — the model correctly
identifies these as NASA space images and uses domain-appropriate vocabulary
("Hubble Space Telescope", "NASA Spitzer") even when it fails on specifics.

#Main failure modes:
- **Hallucination**: model copies training caption patterns but fills in
  wrong specific details (wrong dates, wrong catalog numbers)
- **Over-generalization**: crowded star cluster images default to generic
  "ultraviolet image" descriptions
- **Dataset size**: 168 training images is too few to learn rare object
  types like specific crater names or impact basins

##**Similarity Search — Bonus Feature**
We reuse the ViT encoder (already part of our model) as an image embedding
engine.
* The CLS token output is a 768-dimensional summary of the image.
* Cosine similarity between two CLS vectors measures visual similarity.
* This gives us a Search mode at zero extra cost — no new model needed.
"""

import torch.nn.functional as F

def get_embedding(image: Image.Image) -> torch.Tensor:
    pixel_values = feature_extractor(
        images=image.convert("RGB"), return_tensors="pt"
    ).pixel_values.to(device)
    with torch.no_grad():
        embedding = model_finetuned.encoder(pixel_values).last_hidden_state[:, 0, :]
    return embedding.cpu()

# Build index once
print("Building embedding index...")
embeddings, index_rows = [], []
for i, row in df.iterrows():
    try:
        img = Image.open(
            os.path.join(IMAGES_DIR, os.path.basename(row['image_file_path']))
        ).convert("RGB")
        embeddings.append(get_embedding(img))
        index_rows.append(row)
    except:
        pass

all_embeddings = torch.cat(embeddings, dim=0)
index_df = pd.DataFrame(index_rows).reset_index(drop=True)
print(f"Index built: {len(index_df)} images ✓")

def search_similar(query_image: Image.Image, top_k=3):
    query_emb = get_embedding(query_image)
    sims = F.cosine_similarity(query_emb, all_embeddings)
    top_idx = sims.topk(top_k).indices
    fig, axes = plt.subplots(1, top_k, figsize=(12, 4))
    for ax, idx in zip(axes, top_idx):
        row = index_df.iloc[idx.item()]
        img = Image.open(
            os.path.join(IMAGES_DIR, os.path.basename(row['image_file_path']))
        ).convert("RGB")
        ax.imshow(img)
        ax.set_title(f"sim={sims[idx]:.2f}\n[{row['category']}]\n{row['text'][:50]}", fontsize=7)
        ax.axis('off')
    plt.tight_layout()
    plt.show()

"""##  **Interactive Demo**
A Gradio interface combining both modes:
- **Generate**: upload any space image → get an AI-generated caption
- **Search**: upload any space image → find the 3 most visually similar images
"""

import gradio as gr

def generate_caption_from_model(image, mdl):
    pixel_values = feature_extractor(
        images=image.convert("RGB"), return_tensors="pt"
    ).pixel_values.to(device)
    with torch.no_grad():
        output_ids = mdl.generate(pixel_values, **gen_kwargs)
    return tokenizer.decode(output_ids[0], skip_special_tokens=True).strip()

def run_caption(image):
    return generate_caption_from_model(image, model_finetuned)

def run_search(image):
    query_emb = get_embedding(image.convert("RGB"))
    sims = F.cosine_similarity(query_emb, all_embeddings)
    top_idx = sims.topk(3).indices
    results = []
    for idx in top_idx:
        row = index_df.iloc[idx.item()]
        img = Image.open(
            os.path.join(IMAGES_DIR, os.path.basename(row['image_file_path']))
        ).convert("RGB")
        results.append((img, f"[{row['category']}] sim={sims[idx]:.2f}"))
    return results

with gr.Blocks(title="🚀 Space Caption Generator") as demo:
    gr.Markdown("# 🚀 Space Caption Generator")
    gr.Markdown("Upload a space image to generate a caption or find similar images.")
    input_image = gr.Image(label="Upload space image", type="pil")
    with gr.Tab("Generate Caption"):
        caption_btn = gr.Button("Generate")
        caption_out = gr.Textbox(label="Generated Caption")
        caption_btn.click(run_caption, inputs=input_image, outputs=caption_out)
    with gr.Tab("Search Similar"):
        search_btn  = gr.Button("Search")
        gallery_out = gr.Gallery(label="Similar images", columns=3)
        search_btn.click(run_search, inputs=input_image, outputs=gallery_out)

demo.launch(share=True)